const Constant = {
  // request, response 관련
  OUT_DATA: "OUT_DATA",
  RESULT: "RESULT",
  RESULT_SUCCESS: true,
  RESULT_FAILURE: false,
  OUT_RESULT_MSG: "OUT_RESULT_MSG",
  RESULT_DETAIL: "RESULT_DETAIL",
  IN_DATA_JOSN: "IN_DATA_JOSN",
  IN_LOG_STR: "IN_LOG_STR",

  // RESULT_DETAIL 관련
  PSWD_LIM_ISSUE: "PSWD_LIM_ISSUE",

  // 로그인 관련
  LOGIN_INFO: "LOGIN_INFO",
  SESSION_TIME: "SESSION_TIME",
  AUTH_LIST: "AUTH_LIST",
  FREE_AUTH_LIST: "FREE_AUTH_LIST",

  // 엑셀 관련
  EXCEL_FILENM: "EXCEL_FILENM",
  EXCEL_SHEETNM: "EXCEL_SHEETNM",
  EXCEL_COLUMN: "EXCEL_COLUMN",
  EXCEL_DATA: "EXCEL_DATA",
  EXCEL_UPLOAD_OPTION: "EXCEL_UPLOAD_OPTION",
} as const;

export default Constant;
